    <div class="row">
        <div class="col-sm-4 col-sm-offset-4 my-message">
            <?= $this->flashMessenger()->render('success',['alert','alert-success']);?>
            <?= $this->flashMessenger()->render('warning',['alert','alert-warning']);?>
        </div>
    </div>
    <h2>
        <div style="float:l,eft;width:80%">List of Users</div>
        <div style="float:right;width:20%;text-align:right">
        <a href="<?=$this->url('user',[
            'controller'=>'user',
            'action'=>'add'
        ])?>">Add</a>
        </div>
    </h2>

    <table class="table table-hover">
        <thead>
            <th>STT</th>
            <th>Name</th>
            <th>Email</th>
            <th>Birthdate</th>
            <th>Options</th>
        </thead>
        <tbody>
            <?php 
            $stt = 1;
            foreach($this->users as $user):
            ?>

            <tr>
                <td><?=$stt++?></td>
                <td><?=$user->getFullname()?></td>
                <td><?=$user->getEmail()?></td>
                <td><?=$user->getBirthdate()->format('d-m-Y')?></td>
                <td>
                <a  href="<?=$this->url('user',[
                    'controller'=>'user',
                    'action'=>'edit',
                    'page'=>$user->getId()
                ])?>">Edit</a> | 
                <a  href="<?=$this->url('products',[
                    'controller'=>'product',
                    'action'=>'delete',
                    'page'=>$user->getId()
                ])?>">Delete</a></td>
            </tr>
            <?php endforeach?>
            
        </tbody>
    </table>