<?php
$form = $this->form;

$file = $form->get('file-upload');
$btn = $form->get('btnSubmit');

$form->setAttributes([
    'enctype' => 'multipart/form-data',
    'action' => $this->url('form',[
        'controller'=>'upload-file',
        'action'=>'index'
    ])
]);
$form->prepare();
?>
<style>
.text-danger{
    margin-top:10px
}
.text-danger li{
    list-style-type:none
}
</style>

<div class="row">
    <div class="col-sm-6 col-sm-offset-3">
        <h2>Upload File</h2>
        <?= $this->form()->openTag($form)?>
        <div class="form-group">
            <?=$this->formLabel($file)?>
            <?=$this->formElement($file)?>
            <?=$this->formElementErrors($file,[
                'class'=>'text-danger'])
            ?>
        </div>

        <div class="form-group">
            <?=$this->formRow($btn)?>
        </div>
        <?= $this->form()->closeTag()?>
    </div>
</div>